{
"Error": {
"item": [{
"documentType": "Credit",
"clientOrderLineId": "",
"errorMessage": "Sales document type is not defined"
}]
},
"Success": {
"item": [{
"documentType": "Credit",
"clientOrderLineId": "ITEM10",
"sapOrderNumber": "546321"
},{
"documentType": "Debit",
"clientOrderLineId": "ITEM10",
"sapOrderNumber": "0864407766"
}, {
"documentType": "Credit",
"clientOrderLineId": "ITEM20",
"sapOrderNumber": "546322"
}]
}
}