global with sharing class REST_OrderObject {
    global String action;
    global Integer statusCode;
    global String statusDescription;
    global DateTime LastModifiedDate;
    global Integer PreliminaryOrderIdDevice;
    global Order__c order;
    global String signature;
    global String signature_tech;
    global String signature_terms;
    global String signature_privacy;
    global String signature_storage;
}